### ISSUE TITLE
知识图谱问题

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [chizhu/KGQA_HLM#10]
你这个数据导入后是没有实体是没有名字显示吗
![图片](https://user-images.githubusercontent.com/15922437/68280373-5fd10780-00b0-11ea-8de2-1999fa5dbf55.png)

**Comment by chizhu** [comment]
因为是我以person作为节点名，具体人名写在属性name字段里，你可以点击该节点可以显示出来的

**Comment by ITBOX-ITBOY** [comment]
你可以访问这个看一下
http://www.51showworld.com，我点击了没有

**Comment by chizhu** [comment]
![image](https://user-images.githubusercontent.com/15606803/68280964-93606180-00b1-11ea-8fb7-5d422e35d523.png)
我这边查看就有了

**Comment by chizhu** [comment]
![image](https://user-images.githubusercontent.com/15606803/68281149-fce07000-00b1-11ea-8334-760e61420abf.png)

**Comment by ITBOX-ITBOY** [comment]
出来了，多谢

**Comment by chizhu** [comment]
没事
