### ISSUE TITLE
项目问题

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [chizhu/KGQA_HLM#11]
项目启动后，要多长时间可以访问呢

**Comment by chizhu** [comment]
不超过一分钟把&nbsp; 基本直接可以访问




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ITBOX-ITBOY"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午4:34
收件人: "chizhu/KGQA_HLM"<KGQA_HLM@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [chizhu/KGQA_HLM] 项目问题 (#11)




项目启动后，要多长时间可以访问呢
 
&mdash;

**Comment by ITBOX-ITBOY** [comment]
这个项目的问答是不是是不好用的呀

**Comment by chizhu** [comment]
对&nbsp; 当时做的很简单，只能是固定句式,仅供参考。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ITBOX-ITBOY"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午4:39
收件人: "chizhu/KGQA_HLM"<KGQA_HLM@noreply.github.com&gt;; 
抄送: "林智敏"<214416523@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [chizhu/KGQA_HLM] 项目问题 (#11)




这个项目的问答是不是是不好用的呀
