### ISSUE TITLE
在使用人物关系问答的时候报错

### ISSUE THREAD

**Issue by AsherChan** [chizhu/KGQA_HLM#2]
你好，我在使用人物关系问答的时候报错IndexError: list index out of range，target_array.append(seg_array[1])
IndexError: list index out of range

然后我把ltp.py里面的这行代码注释掉之后又报类似的错误
with open("./spider/images/"+"%s.jpg" % (str(data_array[-1]['p.Name'])), "rb") as image:
IndexError: list index out of range

想问一下作者这是什么原因啊

**Comment by chizhu** [comment]
数组下标越界，目前仅支持xx的xx(关系)是谁？你可能只输入了人名，然后只得到一个长度为一的人名实体数组导致下标越界。这个系统还很初步，谢谢反馈。

**Comment by AsherChan** [comment]
的确只输入人名会出现这样的错误，但是我按照示例输入“贾宝玉的爸爸是谁”的时候也会出现这种错误哦

**Comment by chizhu** [comment]
ltp需要加载模型来进行分词和词性标注，你模型下载好了吗，然后还需查看加载模型路径是否有误。

**Comment by AsherChan** [comment]
发现的确是路径加载问题，谢谢你！

**Comment by AsherChan** [comment]
还有想问一下作者raw_data里面的relation.txt三元组关系抽取是到百科页面抽取的还是小说文本中抽取的，也是用LTP的依存句法抽取吗

**Comment by studyddda** [comment]
您好可以问一下，就是我的ltp路径没有问题也下载好了但是还是有with open("./spider/images/"+"%s.jpg" % (str(data_array[-1]['p.Name'])), "rb") as image:
IndexError: list index out of range
这个问题而且我输入的是贾宝玉的爸爸是谁，格式也对，弄不出来改不了bug，求解
