### ISSUE TITLE
search_name接口返回空

### ISSUE THREAD

**Issue by MrRace** [chizhu/KGQA_HLM#4]
在使用人物关系可视化模块的时候，在搜索框中输入比如查询“林黛玉”。我查看了接口请求，如下GET /search_name?name=%E6%9E%97%E9%BB%9B%E7%8E%89
返回是空的？
```
{"data":[],"links":[]}
```
请问是怎么回事？我尝试搜索的多个名字都是返回空。

**Comment by chizhu** [comment]
这种情况应该是你部署出现问题  打开localhost：7474查看图数据是否创建成功

**Comment by MrRace** [comment]
7474的neo4j服务是开启的。人物关系全貌是有图渲染的结果的。

**Comment by chizhu** [comment]
没有具体报错信息？

**Comment by chizhu** [comment]
我知道了 ，你是少执行一步python create.py 没有创建图数据库。我现在测试都是好的。如果对你有帮助，给个star哈！

**Comment by MrRace** [comment]
现在OK了。其实有些版本上的差异的。比如py2neo你的代码是3.0版本的，目前最近的是4.0版本，有些差异。赞你了！

**Comment by chizhu** [comment]
好哒  谢谢～

**Comment by MrRace** [comment]
另外，怎么生成的三元组关系？你似乎没有介绍relation.txt这个文件是怎么来的？能否详细介绍下？谢谢

**Comment by chizhu** [comment]
关系抽取那块我主要是从百度百科那里爬取  人物百科那有块人际关系的，我直接爬取。然后对于一些缺失关系的进行人工补充。

**Comment by MrRace** [comment]
@chizhu 关系抽取这部分代码，方便一起提供下吗？

**Comment by chizhu** [comment]
抱歉  这个代码当初写的比较乱，后来就不见了。。。不然我就一起传上去撒
