### ISSUE TITLE
使用其他数据Web App仍然显示红楼梦数据

### ISSUE THREAD

**Issue by BrambleXu** [chizhu/KGQA_HLM#5]
你好，关于导入其他数据的问题想请教一下。

我试着把红楼梦的relation.txt换成了三国演义的，数据也能正常录入，Neo4j的web端能看到相关的内容。
但是在启动app后，仍然显示红楼梦的相关信息。如果想要修改的话，请问从哪里入手比较好呢？

**Comment by chizhu** [comment]
是不是整体关系显示那  那个我是读取data.json  这个文件需要你读取neo图数据库全部数据  然后导成我那个json格式  具体可以参考query.py那里面的函数  不过对于选取全部数据的py2neo的执行代码你得自己百度

**Comment by BrambleXu** [comment]
不仅仅是整体关系，人物关系可视化（单独检索某个人的时候），也无法输出三国人物的相关结果

**Comment by chizhu** [comment]
那个是因为html那里我写死了然后   config.py那里我做了家族的匹配替换
